# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: gateway
#   labels:
#     name: gateway
# spec:
#   rules:
#   - host: test.com
#     http:
#       paths:
#       - pathType: Prefix
#         path: "/"
#         backend:
#           service:
#             name: httpserver
#             port: 
#               number: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: httpserver
# spec:
#   selector:
#     app: httpserver
#   ports:
#   - port: 80
#     targetPort: 80
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
spec:
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      containers:
      - name: httpserver
        image: yeahe83/httpserver:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
